# Generated by Django 6.0.5 on 2026-07-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_alter_examattempt_exam_alter_examattempt_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examattempt",
            name="total_marks",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="studentanswer",
            name="marks_awarded",
            field=models.FloatField(default=0),
        ),
    ]
