# Generated by Django 6.0.5 on 2026-07-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_alter_examattempt_total_marks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examattempt",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
