# Generated by Django 6.0.5 on 2026-07-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_alter_examattempt_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["question_number"]},
        ),
        migrations.AddField(
            model_name="question",
            name="question_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="total_marks",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
