# Generated by Django 6.0.5 on 2026-08-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_alter_question_options_question_question_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="negative_marking",
            field=models.BooleanField(
                default=False,
                help_text="Enable negative marking for incorrect answers.",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="negative_marks",
            field=models.FloatField(
                default=0.25, help_text="Marks deducted for each incorrect answer."
            ),
        ),
    ]
