# Generated by Django 6.0.5 on 2026-08-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_exam_negative_marking_exam_negative_marks"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="marks_per_question",
            field=models.FloatField(
                default=1, help_text="Marks awarded for each correct answer."
            ),
        ),
    ]
