# Generated by Django 6.0.5 on 2026-08-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_exam_marks_per_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examattempt",
            name="total_marks",
            field=models.FloatField(default=0),
        ),
    ]
