from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)
from reportlab.lib.styles import getSampleStyleSheet


def build_result_pdf(buffer, attempt):
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    # Header
    elements.append(
        Paragraph("AI Exam Portal – Result Report", styles['Title'])
    )
    elements.append(Spacer(1, 20))

    # Student details
    elements.append(
        Paragraph(
            f"<b>Student:</b> {attempt.student.username}",
            styles['BodyText']
        )
    )

    elements.append(
        Paragraph(
            f"<b>Exam:</b> {attempt.exam.title}",
            styles['BodyText']
        )
    )

    elements.append(
        Paragraph(
            f"<b>Subject:</b> {attempt.exam.subject}",
            styles['BodyText']
        )
    )

    elements.append(
        Paragraph(
            f"<b>Score:</b> {attempt.score}/{attempt.total_marks}",
            styles['BodyText']
        )
    )

    elements.append(
        Paragraph(
            f"<b>Percentage:</b> {attempt.percentage}%",
            styles['BodyText']
        )
    )

    elements.append(
        Paragraph(
            f"<b>Status:</b> {'PASS' if attempt.is_passed else 'FAIL'}",
            styles['BodyText']
        )
    )

    elements.append(
        Paragraph(
            f"<b>Submitted:</b> "
            f"{attempt.submitted_at.strftime('%d %b %Y %I:%M %p')}",
            styles['BodyText']
        )
    )

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "Generated by AI Exam Portal",
            styles['Italic']
        )
    )

    doc.build(elements)